In [1]:
import cv2
import numpy as np

In [3]:
vid=cv2.VideoCapture(0)
f=1

while True:
    f=f+1
    check,frame=vid.read()
    print(frame)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Video Capture",gray)
    x = cv2.waitKey(1)
    if x == ord('b'):
        break

print(f)
vid.release()
cv2.destroyAllWindows()

[[[160 156 167]
  [159 155 166]
  [159 154 166]
  ...
  [182 154 154]
  [174 146 139]
  [173 143 132]]

 [[158 154 163]
  [158 155 165]
  [160 155 166]
  ...
  [179 153 153]
  [170 143 137]
  [167 139 129]]

 [[156 150 158]
  [155 150 158]
  [156 150 159]
  ...
  [173 152 153]
  [168 146 142]
  [167 142 135]]

 ...

 [[ 78  85  67]
  [ 95 101  84]
  [100 102  86]
  ...
  [130 117 109]
  [142 128 120]
  [141 125 118]]

 [[ 72  71  54]
  [ 98  97  80]
  [ 98  94  79]
  ...
  [138 126 115]
  [141 128 119]
  [139 126 118]]

 [[ 83  78  60]
  [102  96  79]
  [ 84  77  62]
  ...
  [137 126 112]
  [143 131 119]
  [141 129 119]]]
[[[162 143 143]
  [162 144 145]
  [160 143 146]
  ...
  [168 143 171]
  [169 142 176]
  [170 141 180]]

 [[156 140 141]
  [160 144 145]
  [160 145 148]
  ...
  [170 145 171]
  [170 144 175]
  [171 143 180]]

 [[145 133 135]
  [146 135 138]
  [147 136 140]
  ...
  [166 143 164]
  [168 144 169]
  [169 144 174]]

 ...

 [[ 93  75  82]
  [ 93  74  81]
  [ 92  72  79]
  ..